#!/usr/bin/env bash

# Core paths and defaults for Andromeda.

if [ -z "${ANDROMEDA_ROOT:-}" ]; then
    _andromeda_env_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    ANDROMEDA_ROOT="$(cd "$_andromeda_env_dir/.." && pwd)"
fi

ANDROMEDA_VERSION="1.0.0"

ANDROMEDA_CONFIG_DIR="$ANDROMEDA_ROOT/config"
ANDROMEDA_RUNTIME_DIR="$ANDROMEDA_ROOT/runtime"
ANDROMEDA_SCRIPTS_DIR="$ANDROMEDA_ROOT/scripts"

ANDROMEDA_SDK_DIR="$ANDROMEDA_RUNTIME_DIR/sdk"
ANDROMEDA_AVD_HOME="$ANDROMEDA_RUNTIME_DIR/avd"
ANDROMEDA_DOWNLOAD_DIR="$ANDROMEDA_RUNTIME_DIR/downloads"
ANDROMEDA_LOG_DIR="$ANDROMEDA_RUNTIME_DIR/logs"
ANDROMEDA_BACKUP_DIR="$ANDROMEDA_RUNTIME_DIR/backups"
ANDROMEDA_PROFILE_DIR="$ANDROMEDA_RUNTIME_DIR/profiles"
ANDROMEDA_ANDROID_USER_HOME="$ANDROMEDA_RUNTIME_DIR/android-user"
ANDROMEDA_TMP_DIR="$ANDROMEDA_RUNTIME_DIR/tmp"

ANDROMEDA_CONFIG_FILE="$ANDROMEDA_CONFIG_DIR/andromeda.json"
ANDROMEDA_PID_FILE="$ANDROMEDA_RUNTIME_DIR/emulator.pid"

ANDROMEDA_DEFAULT_API_LEVEL="36"
ANDROMEDA_DEFAULT_IMAGE_TYPE="google_apis"
ANDROMEDA_DEFAULT_ABI="arm64-v8a"
ANDROMEDA_DEFAULT_DEVICE="pixel_8"
ANDROMEDA_DEFAULT_AVD_NAME="Andromeda_Stable"
ANDROMEDA_DEFAULT_RAM_MB="4096"
ANDROMEDA_DEFAULT_CORES="4"
ANDROMEDA_DEFAULT_GPU="host"
ANDROMEDA_DEFAULT_DISK_SIZE="16G"
ANDROMEDA_DEFAULT_ADB_WAIT_SECONDS="180"
ANDROMEDA_DEFAULT_CMDLINE_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-mac-14742923_latest.zip"
ANDROMEDA_DEFAULT_CMDLINE_TOOLS_SHA256=""

ANDROMEDA_API_LEVEL="${ANDROMEDA_API_LEVEL:-$ANDROMEDA_DEFAULT_API_LEVEL}"
ANDROMEDA_IMAGE_TYPE="${ANDROMEDA_IMAGE_TYPE:-$ANDROMEDA_DEFAULT_IMAGE_TYPE}"
ANDROMEDA_ABI="${ANDROMEDA_ABI:-$ANDROMEDA_DEFAULT_ABI}"
ANDROMEDA_DEVICE="${ANDROMEDA_DEVICE:-$ANDROMEDA_DEFAULT_DEVICE}"
ANDROMEDA_AVD_NAME="${ANDROMEDA_AVD_NAME:-$ANDROMEDA_DEFAULT_AVD_NAME}"
ANDROMEDA_RAM_MB="${ANDROMEDA_RAM_MB:-$ANDROMEDA_DEFAULT_RAM_MB}"
ANDROMEDA_CORES="${ANDROMEDA_CORES:-$ANDROMEDA_DEFAULT_CORES}"
ANDROMEDA_GPU="${ANDROMEDA_GPU:-$ANDROMEDA_DEFAULT_GPU}"
ANDROMEDA_DISK_SIZE="${ANDROMEDA_DISK_SIZE:-$ANDROMEDA_DEFAULT_DISK_SIZE}"
ANDROMEDA_ADB_WAIT_SECONDS="${ANDROMEDA_ADB_WAIT_SECONDS:-$ANDROMEDA_DEFAULT_ADB_WAIT_SECONDS}"
ANDROMEDA_CMDLINE_TOOLS_URL="${ANDROMEDA_CMDLINE_TOOLS_URL:-$ANDROMEDA_DEFAULT_CMDLINE_TOOLS_URL}"
ANDROMEDA_CMDLINE_TOOLS_SHA256="${ANDROMEDA_CMDLINE_TOOLS_SHA256:-$ANDROMEDA_DEFAULT_CMDLINE_TOOLS_SHA256}"

andromeda_android_image() {
    printf 'system-images;android-%s;%s;%s\n' "$ANDROMEDA_API_LEVEL" "$ANDROMEDA_IMAGE_TYPE" "$ANDROMEDA_ABI"
}

andromeda_platform_package() {
    printf 'platforms;android-%s\n' "$ANDROMEDA_API_LEVEL"
}

andromeda_export_android_env() {
    export ANDROID_HOME="$ANDROMEDA_SDK_DIR"
    export ANDROID_SDK_ROOT="$ANDROMEDA_SDK_DIR"
    export ANDROID_AVD_HOME="$ANDROMEDA_AVD_HOME"
    export ANDROID_USER_HOME="$ANDROMEDA_ANDROID_USER_HOME"
    export ANDROID_EMULATOR_HOME="$ANDROMEDA_ANDROID_USER_HOME"

    _andromeda_path_add "$ANDROMEDA_SDK_DIR/cmdline-tools/latest/bin"
    _andromeda_path_add "$ANDROMEDA_SDK_DIR/platform-tools"
    _andromeda_path_add "$ANDROMEDA_SDK_DIR/emulator"
}

_andromeda_path_add() {
    case ":$PATH:" in
        *":$1:"*) ;;
        *) PATH="$1:$PATH" ;;
    esac
    export PATH
}

andromeda_ensure_dirs() {
    mkdir -p \
        "$ANDROMEDA_CONFIG_DIR" \
        "$ANDROMEDA_RUNTIME_DIR" \
        "$ANDROMEDA_SCRIPTS_DIR" \
        "$ANDROMEDA_SDK_DIR" \
        "$ANDROMEDA_AVD_HOME" \
        "$ANDROMEDA_DOWNLOAD_DIR" \
        "$ANDROMEDA_LOG_DIR" \
        "$ANDROMEDA_BACKUP_DIR" \
        "$ANDROMEDA_PROFILE_DIR" \
        "$ANDROMEDA_ANDROID_USER_HOME" \
        "$ANDROMEDA_TMP_DIR"
}

andromeda_export_android_env
